### ISSUE TITLE
ACVD crashes after closing second window

### ISSUE THREAD

**Issue by RogersDoug** [valette/ACVD#12]
Windows 10, x64 VS2015, Debug

Windows crashes when running ACVD with display on.  

repro:

Run ACVD  
close first window that pops up
close second window

What is the process for getting a remerged mesh with display enabled.  I can't find any docs that describe the steps.

Setting the variable 'Display' to 0 runs without crashing.

**Comment by valette** [comment]
Well this should work... Is this issue related to issue #11

**Comment by RogersDoug** [comment]
It is not related.  Crashes with bunny.ply the same way.

**Comment by valette** [comment]
Have you tried not to close the windows but to press the 'e' key to let the program continue?

**Comment by RogersDoug** [comment]
Does not crash using 'e' key.  While the code for this project is exceptional, the documentation could be improved.
