### ISSUE TITLE
VTK 7.x removes vtkstd

### ISSUE THREAD

**Issue by get9** [valette/ACVD#20]
While trying to compile this project against the latest VTK (v7.1.0), I ran into a compile error with `vtkstd` being used. It appears that this has been [deprecated](https://gitlab.kitware.com/vtk/vtk/commit/42e508b397ead9224e15022d5527087cc08ff26c) and should probably be changed to the regular `std` namespace. Doing so in  `VolumeProcessing/vtkOOCMetaImageReader.cxx` made the build pass again.

**Comment by valette** [comment]
Commit fbfb9689647c18195d4f14341dd1f998c6a0c4f8 removes the dependency to vtkstd. Is it fixed for you?

**Comment by get9** [comment]
Yep, that fixes it. That's pretty much what I did to fix it locally. I'll go ahead and close this.
