### ISSUE TITLE
Error in the doc

### ISSUE THREAD

**Issue by delmottea** [valette/ACVD#22]
Hello,
Just a small detail, but on the command line interface, the doc specify :
-d 0/1/2 : enables display (default : 0)
but the real default value is 1.

Should change the default value in DiscreteRemeshing/Examples/ACVD.cxx:60 and DiscreteRemeshing/Examples/ACVDQ.cxx:80, or change the doc in DiscreteRemeshing/Examples/ACVD.cxx:87 and DiscreteRemeshing/Examples/ACVDQ.cxx:103

**Comment by valette** [comment]
Problem solved since commit 38a8539d260ed898154d9577cffe105e62c9b163
