### ISSUE TITLE
Missing file when compiling

### ISSUE THREAD

**Issue by isaacengel** [valette/ACVD#25]
Hello,

I am trying to compile the latest version of ACVD with Visual Studio 2017. However, when I build the solution, I get a lot of the following:

```
fatal error LNK1181: cannot open input file 'vtkChartsCore.lib'
fatal error LNK1181: cannot open input file '..\..\bin\Release\vtkSurface.lib'
fatal error LNK1181: cannot open input file '..\..\bin\Release\vtkDiscreteRemeshing.lib'
```

What could be the cause?
Note: I am using VTK 7.1.1

Thanks!

**Comment by valette** [comment]
Hi, do you still have this problem?
