### ISSUE TITLE
Differents results between MacOS et Windows 10

### ISSUE THREAD

**Issue by Toon34** [valette/ACVD#27]
Hello !

I use MacOS X Mojave 10.14.4 and Windows 10 up to date.
In my case, i need to use ACVD for deploy a complex deformable sphere.
I search in this github repository but i did not find anything...
Has anyone ever encountered any differences?

With the same input...

Windows ouput :
> Mesh with 3040 polygons, 1522 points, 4560 edges
Bounding Box: [94.6748, 63.8625, -75.726]
              [101.292, 70.7261, -66.4477] 
The mesh is made only of 3040 triangles
0 non-manifold edges and 0 boundary edges
The mesh has 1 connected components
 Valences entropy: 1.64355
0 disconnected vertices, 1522 connected vertices
46.6491 percent of irregular vertices
Mesh geometry qualitity:
  AngleMin=24.1465
  AverageMinAngle=46.4177
  Qmin=0.437835
  Qav=0.827767
  P30=0.372807

Mac ouput :
> Mesh with 3040 polygons, 1522 points, 4560 edges
Bounding Box: [94.6693, 63.8688, -75.7243]
              [101.3, 70.7324, -66.4492] 
The mesh is made only of 3040 triangles
0 non-manifold edges and 0 boundary edges
The mesh has 1 connected components
 Valences entropy: 1.66243
0 disconnected vertices, 1522 connected vertices
47.7004 percent of irregular vertices
Mesh geometry qualitity:
  AngleMin=19.2219
  AverageMinAngle=46.4299
  Qmin=0.312611
  Qav=0.827966
  P30=0.307018

Regards

**Comment by valette** [comment]
Hi, sorry, I just saw your comment. Maybe this comes fom the random initialization. Let me think about it...

**Comment by djelouze** [comment]
I just filled an issue related to random_shuffle, maybe it will be the opportunity to kill two birds with one stone :) 

I also arrived to the conclusion that the unspecified random generator may result to unreproducible cases !

**Comment by valette** [comment]
Yes!
Commit 4fe21065997900c2ede0b25ec12a1daac814ae0e should fix this issue. Please reopen this issue if you still have a similar problem.
