### ISSUE TITLE
Example code usage with data

### ISSUE THREAD

**Issue by BinWang0213** [valette/ACVD#29]
Thanks for sharing this nice code. I'm new to this tool. I found there are many tools here:
1. ACVD
2. ACVDQ
3. AnisotropicRemeshing
4. AnisotropicRemeshingQ
5. ManifoldSimplification
6. VolumeAnalysis
7. etc

Can you add few simple tutorials/examples with data in Readme.md to show how to use your codes for each of them? I think hand model and fandisk in your paper are good cases.
 
I found this Python implementation of ACVD is a good example. 

https://github.com/pyvista/pyacvd

**Comment by valette** [comment]
I have added a few examples of remeshing in the Readme. This provides an example for ACVD, ACVDQ and AnisotropicRemeshingQ. Will continue to document other tools....
Closing, but if you miss one particular example, you can reopen the issue!
