### ISSUE TITLE
Extra build dependencies needed

### ISSUE THREAD

**Issue by phpHavok** [valette/ACVD#32]
I just built this today, and I needed to install a few extra dependencies that weren't listed in order to get it to work.

I'm using Arch Linux (5.7.10-arch1-1) and these extra packages were needed:
- gdal
- unixodbc
- pdal
- pugixml

This comment helped a lot:
https://github.com/PointCloudLibrary/pcl/issues/2616#issuecomment-557153849

Thanks!

**Comment by valette** [comment]
So it seems to be an issue with Arch Linux not correctly installing VTK dependencies, so it is not really an issue with ACVD. Closing, please reopen if I got this wrong.
