### ISSUE TITLE
VTK 9 Compilation Error

### ISSUE THREAD

**Issue by qaler** [valette/ACVD#33]
I am trying to build ACVD using latest VTK 9.0 library.

But when building against [vtkSurfaceBase.h](https://github.com/valette/ACVD/blob/master/Common/vtkSurfaceBase.h#L449-L451) , the compiler aborts with errors: 

```c++
vtkIdType n,*pts;
this->Polys->GetCell(this->Cells->GetCellLocation(face),n,pts);
```

The error message is:
```
“GetCellLocation” is not a member of vtkPolyData_detail::CellMap
```

How may I fix this?

**Comment by valette** [comment]
Hi,
Pull request #30 has been proposed, I am checking it right now

**Comment by valette** [comment]
Hi, I have created a branch for vtk9 : [/valette/ACVD/tree/vtk9](/valette/ACVD/tree/vtk9) 
Could you test it?

**Comment by valette** [comment]
The master branch should now compile with vtk9
