### ISSUE TITLE
Clustered mesh vertices are not equal to input number of clusters sometimes

### ISSUE THREAD

**Issue by lppllppl920** [valette/ACVD#34]
Dear author,

Sometimes I found that the specified number of clusters is not equal to the number of vertices in the output mesh. Is it something that is inherent in this method or is it a bug?

Thank you!

Xingtong

**Comment by valette** [comment]
Do you have an example to share?

**Comment by lppllppl920** [comment]
Sorry. I realized that was a bug in my own code.
