### ISSUE TITLE
random_shuffle deprecated in c++17

### ISSUE THREAD

**Issue by djelouze** [valette/ACVD#38]
In c++17, which is default standard for gcc 11, the random_shuffle function is deprecated : https://en.cppreference.com/w/cpp/algorithm/random_shuffle (this page also gives alternative implementation with random_device which is c++11 compliant)

Only one occurrence is found in the code :
https://github.com/valette/ACVD/blob/d3e1f6c14f35b19c3815ae96299147c8d33cb22c/Common/vtkUniformClustering.h#L1195

Note1 gcc still build it but MSVC does not.
Note2 'register' keyword is unused in c++17 and many warnings are thrown

**Comment by valette** [comment]
Thank you for the heads up! This should be fixed now.
