### ISSUE TITLE
vtkDiscreteRemeshing missing

### ISSUE THREAD

**Issue by jordium** [valette/ACVD#43]
When I create the solution with cmake it doesn't generate the vtkDiscreteRemeshing project, and when I compile I'm missing vtkDiscreteRemeshing.lib

**Comment by valette** [comment]
Hello,
since  commit 8b8bd6e94fd76f606e70f5379a369f096d2bf23c, the vtkDiscreteRemeshing has been removed.
I guess your issue comes from the fact that your CMake files are not new.
Can you try removing CMakeCache.txt and run cmake again?

**Comment by valette** [comment]
Closing, feel free to reopen if bug is still here!
