### ISSUE TITLE
MSVC compiler complains about int to vtkIdType conversion

### ISSUE THREAD

**Issue by YangShen398** [valette/ACVD#45]
Hi ACVD developers,

I am building ACVD using VTK 9 using MSVC (16.11.11) from Visual Studio 2019 for x64 architecture and the compilation failed due to the error "int to vtkIdType conversion" on line [119](https://github.com/valette/ACVD/blob/f6fb3a0b2b9433f7362021476c93869d2acdb738/DiscreteRemeshing/vtkVerticesProcessing.h#L119) in vtkVerticesProcessing.h.

It seems like easy fix. I just replace line [118](https://github.com/valette/ACVD/blob/f6fb3a0b2b9433f7362021476c93869d2acdb738/DiscreteRemeshing/vtkVerticesProcessing.h#L118) with
// int NumberOfEdges,*Edges,i;
vtkIdType NumberOfEdges,*Edges,i;

Then, the complication is succesful.

**Comment by valette** [comment]
Hi,
I have just pushed commit 5cd56db, does this help?

**Comment by YangShen398** [comment]
> Hi, I have just pushed commit [5cd56db](https://github.com/valette/ACVD/commit/5cd56dbab8de1b144dcb58d74dedff58fa520c92), does this help?

yes
