### ISSUE TITLE
In Ubuntu 20.04, What version of VTK do i need to install?

### ISSUE THREAD

**Issue by mo1shang** [valette/ACVD#46]
I installed vtk7 in ubuntu20.04 through apt, but an error was reported in the cmake process, I am not quite sure why, may I ask which version of vtk library ACVD relies on?

**Comment by valette** [comment]
vtk7 seems quite old. Are there any more recent versions available? Can you share the CMake output?

**Comment by mo1shang** [comment]
I originally thought that ACVD needed older versions of vtk because some of the documents in ACVD were released quite early. 
But I just installed the latest version of vtk (vtk9.x.x), the ACVD compilation process is no longer reporting errors, and I have successfully run the executable. 
Thank you for your work, it is very helpful to me.

**Comment by valette** [comment]
You're wellcome!

**Comment by valette** [comment]
Fixed
